[package]
name = "error-forge-derive"
version = "0.1.0"
edition = "2021"
description = "Derive macros for the error-forge crate"
license = "Apache-2.0"
authors = [
    "James Gober <codeca@jamesgober.dev>"
]

[lib]
proc-macro = true

[dependencies]
syn = "1.0"
quote = "1.0"
proc-macro2 = "1.0"
