[package]
name = "error-forge"
version = "0.6.3"
edition = "2021"
readme = "README.md"
license = "Apache-2.0"

authors = [
    "James Gober <codeca@jamesgober.dev>"
]

description = "A flexible, high-performance Rust error framework for defining, formatting, chaining, and managing rich custom errors across large-scale applications."

keywords = [
    "error",
    "error-handling",
    "rust",
    "framework",
    "custom-errors"
]

categories = [
    "rust-patterns",
    "development-tools::debugging",
    "data-structures"
]

documentation = "https://docs.rs/error-forge"
repository = "https://github.com/jamesgober/error-forge"
homepage = "https://github.com/jamesgober/error-forge"

# Configuration for docs.rs
[package.metadata.docs.rs]
# Enable all features when building docs
all-features = true
# Enable specific features for documentation
features = ["derive", "serde", "console", "backtrace"]
# Set specific rustdoc flags
rustdoc-args = ["--cfg", "docsrs"]


[dependencies]
thiserror = "1.0"
paste = "1.0"
error-forge-derive = {version = "0.2.1", path = "./error-forge-derive", optional = true }
serde = { version = "1.0", optional = true, features = ["derive"] }

[features]
default = []
serde = ["dep:serde"]
derive = ["error-forge-derive"]
console = []
backtrace = []

[workspace]
members = ["error-forge-derive"]

[dev-dependencies]
serde_json = "1.0"
