[package]
name = "error-forge"
version = "0.4.0"
edition = "2021"
readme = "README.md"
license = "Apache-2.0"

authors = [
    "James Gober <codeca@jamesgober.dev>"
]

description = "A flexible, high-performance Rust error framework for defining, formatting, chaining, and managing rich custom errors across large-scale applications."

keywords = [
    "error",
    "error-handling",
    "rust",
    "framework",
    "custom-errors"
]

categories = [
    "rust-patterns",
    "development-tools::debugging",
    "data-structures"
]

documentation = "https://docs.rs/error-forge"
repository = "https://github.com/jamesgober/error-forge"
homepage = "https://github.com/jamesgober/error-forge"



[dependencies]
thiserror = "1.0"
paste = "1.0"
error-forge-derive = { path = "./error-forge-derive", optional = true }

[features]
default = []
serde = []
derive = ["error-forge-derive"]
console = []
backtrace = []

[workspace]
members = ["error-forge-derive"]

[dev-dependencies]
serde_json = "1.0"

[package.metadata.docs.rs]
features = ["derive", "serde", "console", "backtrace"]
rustdoc-args = ["--cfg", "docsrs"]
